# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24077d96940a6596cd3b412046e8decec5661ed7a1d73cccf9231ca1473ea99cfb3d5c9bf8f22c183eb62912f49c0be1348858efe3b0f4eaf4845d41096cd732
  public_site_secret_key: 24077d96940a6596cd3b412046e8decec5661ed7a1d73cccf9231ca1473ea99cfb3d5c9bf8f22c183eb62912f49c0be1348858efe3b0f4eaf4845d41096cd732
  stripe_secret_key: sk_test_fAxz44CRUtvmuta7PucaV0CN
  stripe_publishable_key: pk_test_m62AAtn1fQgFLjXjqvYwEZiP
  twilio_account_sid: AC1b7c963a58b9b7b08ab26241e6dd9901
  twilio_auth_token: f00b7ce4981640c50a8cfdf79c919511
  s3_access_key_id: <%= ENV["WEDDING_EXPO_S3_ID"] %>
  s3_secret_access_key: <%= ENV["WEDDING_EXPO_S3_KEY"] %>
  campaign_monitor_key: <%= ENV["WEDDING_EXPO_CM_KEY"] %>
  campaign_monitor_client: <%= ENV["WEDDING_EXPO_CM_CLIENT"] %>

test:
  secret_key_base: 05425862223b5b82f48a60bc18bc0cbaef2f35c5bc3638ac94d9056dd0433ed67cb4b5721c2cd3eba7f76074c4977c893e5c98372e6a2150469bca4934e4fd46
  public_site_secret_key: test_secret_key
  stripe_secret_key: not_used
  stripe_publishable_key: not_used
  twilio_account_sid: not_used
  twilio_auth_token: not_used

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  public_site_secret_key: <%= ENV["PUBLIC_SITE_SECRET_KEY"] %>
  ses_access_key_id: <%= ENV["SES_ID"] %>
  ses_secret_access_key: <%= ENV["SES_KEY"] %>
  s3_access_key_id: <%= ENV["S3_ID"] %>
  s3_secret_access_key: <%= ENV["S3_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PK"] %>
  stripe_secret_key: <%= ENV["STRIPE_SK"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  campaign_monitor_key: <%= ENV["WEDDING_EXPO_CM_KEY"] %>
  campaign_monitor_client: <%= ENV["WEDDING_EXPO_CM_CLIENT"] %>
